export const MAX_LISTITEM_LENGTH = 20;
export const LANGUAGES = {
  KOREAN: {
    CODE: "ko",
    DISPLAY: "한국어",
  },
  ENGLISH: { CODE: "en", DISPLAY: "English" },
  AFAR: { CODE: "aa", DISPLAY: "Afar" },
  ABKHAZIAN: { CODE: "ab", DISPLAY: "Abkhazian" },
  AVESTAN: { CODE: "ae", DISPLAY: "Avestan" },
  AFRIKAANS: { CODE: "af", DISPLAY: "Afrikaans" },
  AKAN: { CODE: "ak", DISPLAY: "Akan" },
  AMHARIC: { CODE: "am", DISPLAY: "Amharic" },
  ARAGONESE: { CODE: "an", DISPLAY: "Aragonese" },
  ARABIC: { CODE: "ar", DISPLAY: "Arabic" },
  ASSAMESE: { CODE: "as", DISPLAY: "Assamese" },
  AVARIC: { CODE: "av", DISPLAY: "Avaric" },
  AYMARA: { CODE: "ay", DISPLAY: "Aymara" },
  AZERBAIJANI: { CODE: "az", DISPLAY: "Azerbaijani" },
  BASHKIR: { CODE: "ba", DISPLAY: "Bashkir" },
  BELARUSIAN: { CODE: "be", DISPLAY: "Belarusian" },
  BULGARIAN: { CODE: "bg", DISPLAY: "Bulgarian" },
  "BIHARI LANGUAGES": { CODE: "bh", DISPLAY: "Bihari languages" },
  BAMBARA: { CODE: "bm", DISPLAY: "Bambara" },
  BISLAMA: { CODE: "bi", DISPLAY: "Bislama" },
  BENGALI: { CODE: "bn", DISPLAY: "Bengali" },
  TIBETAN: { CODE: "bo", DISPLAY: "Tibetan" },
  BRETON: { CODE: "br", DISPLAY: "Breton" },
  BOSNIAN: { CODE: "bs", DISPLAY: "Bosnian" },
  "CATALAN; VALENCIAN": { CODE: "ca", DISPLAY: "Catalan; Valencian" },
  CHECHEN: { CODE: "ce", DISPLAY: "Chechen" },
  CHAMORRO: { CODE: "ch", DISPLAY: "Chamorro" },
  CORSICAN: { CODE: "co", DISPLAY: "Corsican" },
  CREE: { CODE: "cr", DISPLAY: "Cree" },
  CZECH: { CODE: "cs", DISPLAY: "Czech" },
  "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic": {
    CODE: "cu",
    DISPLAY:
      "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
  },
  CHUVASH: { CODE: "cv", DISPLAY: "Chuvash" },
  WELSH: { CODE: "cy", DISPLAY: "Welsh" },
  DANISH: { CODE: "da", DISPLAY: "Danish" },
  GERMAN: { CODE: "de", DISPLAY: "German" },
  "Divehi; Dhivehi; Maldivian": {
    CODE: "dv",
    DISPLAY: "Divehi; Dhivehi; Maldivian",
  },
  DZONGKHA: { CODE: "dz", DISPLAY: "Dzongkha" },
  EWE: { CODE: "ee", DISPLAY: "Ewe" },
  "GREEK, MODERN (1453-)": { CODE: "el", DISPLAY: "Greek, Modern (1453-)" },
  ESPERANTO: { CODE: "eo", DISPLAY: "Esperanto" },
  "SPANISH; CASTILIAN": { CODE: "es", DISPLAY: "Spanish; Castilian" },
  ESTONIAN: { CODE: "et", DISPLAY: "Estonian" },
  BASQUE: { CODE: "eu", DISPLAY: "Basque" },
  PERSIAN: { CODE: "fa", DISPLAY: "Persian" },
  FULAH: { CODE: "ff", DISPLAY: "Fulah" },
  FINNISH: { CODE: "fi", DISPLAY: "Finnish" },
  FIJIAN: { CODE: "fj", DISPLAY: "Fijian" },
  FAROESE: { CODE: "fo", DISPLAY: "Faroese" },
  FRENCH: { CODE: "fr", DISPLAY: "French" },
  "WESTERN FRISIAN": { CODE: "fy", DISPLAY: "Western Frisian" },
  IRISH: { CODE: "ga", DISPLAY: "Irish" },
  "GAELIC; SCOTTISH GAELIC": { CODE: "gd", DISPLAY: "Gaelic; Scottish Gaelic" },
  GALICIAN: { CODE: "gl", DISPLAY: "Galician" },
  GUARANI: { CODE: "gn", DISPLAY: "Guarani" },
  GUJARATI: { CODE: "gu", DISPLAY: "Gujarati" },
  MANX: { CODE: "gv", DISPLAY: "Manx" },
  HAUSA: { CODE: "ha", DISPLAY: "Hausa" },
  HEBREW: { CODE: "he", DISPLAY: "Hebrew" },
  HINDI: { CODE: "hi", DISPLAY: "Hindi" },
  "HIRI MOTU": { CODE: "ho", DISPLAY: "Hiri Motu" },
  CROATIAN: { CODE: "hr", DISPLAY: "Croatian" },
  "HAITIAN; HAITIAN CREOLE": { CODE: "ht", DISPLAY: "Haitian; Haitian Creole" },
  HUNGARIAN: { CODE: "hu", DISPLAY: "Hungarian" },
  ARMENIAN: { CODE: "hy", DISPLAY: "Armenian" },
  HERERO: { CODE: "hz", DISPLAY: "Herero" },
  "Interlingua (International Auxiliary Language Association)": {
    CODE: "ia",
    DISPLAY: "Interlingua (International Auxiliary Language Association)",
  },
  INDONESIAN: { CODE: "id", DISPLAY: "Indonesian" },
  "INTERLINGUE; OCCIDENTAL": { CODE: "ie", DISPLAY: "Interlingue; Occidental" },
  IGBO: { CODE: "ig", DISPLAY: "Igbo" },
  "SICHUAN YI; NUOSU": { CODE: "ii", DISPLAY: "Sichuan Yi; Nuosu" },
  INUPIAQ: { CODE: "ik", DISPLAY: "Inupiaq" },
  IDO: { CODE: "io", DISPLAY: "Ido" },
  ICELANDIC: { CODE: "is", DISPLAY: "Icelandic" },
  ITALIAN: { CODE: "it", DISPLAY: "Italian" },
  INUKTITUT: { CODE: "iu", DISPLAY: "Inuktitut" },
  JAPANESE: { CODE: "ja", DISPLAY: "Japanese" },
  JAVANESE: { CODE: "jv", DISPLAY: "Javanese" },
  GEORGIAN: { CODE: "ka", DISPLAY: "Georgian" },
  KONGO: { CODE: "kg", DISPLAY: "Kongo" },
  "KIKUYU; GIKUYU": { CODE: "ki", DISPLAY: "Kikuyu; Gikuyu" },
  "KUANYAMA; KWANYAMA": { CODE: "kj", DISPLAY: "Kuanyama; Kwanyama" },
  KAZAKH: { CODE: "kk", DISPLAY: "Kazakh" },
  "Kalaallisut; Greenlandic": {
    CODE: "kl",
    DISPLAY: "Kalaallisut; Greenlandic",
  },
  "CENTRAL KHMER": { CODE: "km", DISPLAY: "Central Khmer" },
  KANNADA: { CODE: "kn", DISPLAY: "Kannada" },
  KANURI: { CODE: "kr", DISPLAY: "Kanuri" },
  KASHMIRI: { CODE: "ks", DISPLAY: "Kashmiri" },
  KURDISH: { CODE: "ku", DISPLAY: "Kurdish" },
  KOMI: { CODE: "kv", DISPLAY: "Komi" },
  CORNISH: { CODE: "kw", DISPLAY: "Cornish" },
  "KIRGHIZ; KYRGYZ": { CODE: "ky", DISPLAY: "Kirghiz; Kyrgyz" },
  LATIN: { CODE: "la", DISPLAY: "Latin" },
  "Luxembourgish; Letzeburgesch": {
    CODE: "lb",
    DISPLAY: "Luxembourgish; Letzeburgesch",
  },
  GANDA: { CODE: "lg", DISPLAY: "Ganda" },
  "Limburgan; Limburger; Limburgish": {
    CODE: "li",
    DISPLAY: "Limburgan; Limburger; Limburgish",
  },
  LINGALA: { CODE: "ln", DISPLAY: "Lingala" },
  LAO: { CODE: "lo", DISPLAY: "Lao" },
  LITHUANIAN: { CODE: "lt", DISPLAY: "Lithuanian" },
  "LUBA-KATANGA": { CODE: "lu", DISPLAY: "Luba-Katanga" },
  LATVIAN: { CODE: "lv", DISPLAY: "Latvian" },
  MALAGASY: { CODE: "mg", DISPLAY: "Malagasy" },
  MARSHALLESE: { CODE: "mh", DISPLAY: "Marshallese" },
  MAORI: { CODE: "mi", DISPLAY: "Maori" },
  MACEDONIAN: { CODE: "mk", DISPLAY: "Macedonian" },
  MALAYALAM: { CODE: "ml", DISPLAY: "Malayalam" },
  MONGOLIAN: { CODE: "mn", DISPLAY: "Mongolian" },
  MARATHI: { CODE: "mr", DISPLAY: "Marathi" },
  MALAY: { CODE: "ms", DISPLAY: "Malay" },
  MALTESE: { CODE: "mt", DISPLAY: "Maltese" },
  BURMESE: { CODE: "my", DISPLAY: "Burmese" },
  NAURU: { CODE: "na", DISPLAY: "Nauru" },
  "Bokmål, Norwegian; Norwegian Bokmål": {
    CODE: "nb",
    DISPLAY: "Bokmål, Norwegian; Norwegian Bokmål",
  },
  "Ndebele, North; North Ndebele": {
    CODE: "nd",
    DISPLAY: "Ndebele, North; North Ndebele",
  },
  NEPALI: { CODE: "ne", DISPLAY: "Nepali" },
  NDONGA: { CODE: "ng", DISPLAY: "Ndonga" },
  "DUTCH; FLEMISH": { CODE: "nl", DISPLAY: "Dutch; Flemish" },
  "Norwegian Nynorsk; Nynorsk, Norwegian": {
    CODE: "nn",
    DISPLAY: "Norwegian Nynorsk; Nynorsk, Norwegian",
  },
  NORWEGIAN: { CODE: "no", DISPLAY: "Norwegian" },
  "Ndebele, South; South Ndebele": {
    CODE: "nr",
    DISPLAY: "Ndebele, South; South Ndebele",
  },
  "NAVAJO; NAVAHO": { CODE: "nv", DISPLAY: "Navajo; Navaho" },
  "CHICHEWA; CHEWA; NYANJA": { CODE: "ny", DISPLAY: "Chichewa; Chewa; Nyanja" },
  "OCCITAN (POST 1500)": { CODE: "oc", DISPLAY: "Occitan (post 1500)" },
  OJIBWA: { CODE: "oj", DISPLAY: "Ojibwa" },
  OROMO: { CODE: "om", DISPLAY: "Oromo" },
  ORIYA: { CODE: "or", DISPLAY: "Oriya" },
  "OSSETIAN; OSSETIC": { CODE: "os", DISPLAY: "Ossetian; Ossetic" },
  "PANJABI; PUNJABI": { CODE: "pa", DISPLAY: "Panjabi; Punjabi" },
  PALI: { CODE: "pi", DISPLAY: "Pali" },
  POLISH: { CODE: "pl", DISPLAY: "Polish" },
  "PUSHTO; PASHTO": { CODE: "ps", DISPLAY: "Pushto; Pashto" },
  PORTUGUESE: { CODE: "pt", DISPLAY: "Portuguese" },
  QUECHUA: { CODE: "qu", DISPLAY: "Quechua" },
  ROMANSH: { CODE: "rm", DISPLAY: "Romansh" },
  RUNDI: { CODE: "rn", DISPLAY: "Rundi" },
  "Romanian; Moldavian; Moldovan": {
    CODE: "ro",
    DISPLAY: "Romanian; Moldavian; Moldovan",
  },
  RUSSIAN: { CODE: "ru", DISPLAY: "Russian" },
  KINYARWANDA: { CODE: "rw", DISPLAY: "Kinyarwanda" },
  SANSKRIT: { CODE: "sa", DISPLAY: "Sanskrit" },
  SARDINIAN: { CODE: "sc", DISPLAY: "Sardinian" },
  SINDHI: { CODE: "sd", DISPLAY: "Sindhi" },
  "NORTHERN SAMI": { CODE: "se", DISPLAY: "Northern Sami" },
  SANGO: { CODE: "sg", DISPLAY: "Sango" },
  "SINHALA; SINHALESE": { CODE: "si", DISPLAY: "Sinhala; Sinhalese" },
  SLOVAK: { CODE: "sk", DISPLAY: "Slovak" },
  SLOVENIAN: { CODE: "sl", DISPLAY: "Slovenian" },
  SAMOAN: { CODE: "sm", DISPLAY: "Samoan" },
  SHONA: { CODE: "sn", DISPLAY: "Shona" },
  SOMALI: { CODE: "so", DISPLAY: "Somali" },
  ALBANIAN: { CODE: "sq", DISPLAY: "Albanian" },
  SERBIAN: { CODE: "sr", DISPLAY: "Serbian" },
  SWATI: { CODE: "ss", DISPLAY: "Swati" },
  "SOTHO, SOUTHERN": { CODE: "st", DISPLAY: "Sotho, Southern" },
  SUNDANESE: { CODE: "su", DISPLAY: "Sundanese" },
  SWEDISH: { CODE: "sv", DISPLAY: "Swedish" },
  SWAHILI: { CODE: "sw", DISPLAY: "Swahili" },
  TAMIL: { CODE: "ta", DISPLAY: "Tamil" },
  TELUGU: { CODE: "te", DISPLAY: "Telugu" },
  TAJIK: { CODE: "tg", DISPLAY: "Tajik" },
  THAI: { CODE: "th", DISPLAY: "Thai" },
  TIGRINYA: { CODE: "ti", DISPLAY: "Tigrinya" },
  TURKMEN: { CODE: "tk", DISPLAY: "Turkmen" },
  TAGALOG: { CODE: "tl", DISPLAY: "Tagalog" },
  TSWANA: { CODE: "tn", DISPLAY: "Tswana" },
  "TONGA (TONGA ISLANDS)": { CODE: "to", DISPLAY: "Tonga (Tonga Islands)" },
  TURKISH: { CODE: "tr", DISPLAY: "Turkish" },
  TSONGA: { CODE: "ts", DISPLAY: "Tsonga" },
  TATAR: { CODE: "tt", DISPLAY: "Tatar" },
  TWI: { CODE: "tw", DISPLAY: "Twi" },
  TAHITIAN: { CODE: "ty", DISPLAY: "Tahitian" },
  "UIGHUR; UYGHUR": { CODE: "ug", DISPLAY: "Uighur; Uyghur" },
  UKRAINIAN: { CODE: "uk", DISPLAY: "Ukrainian" },
  URDU: { CODE: "ur", DISPLAY: "Urdu" },
  UZBEK: { CODE: "uz", DISPLAY: "Uzbek" },
  VENDA: { CODE: "ve", DISPLAY: "Venda" },
  VIETNAMESE: { CODE: "vi", DISPLAY: "Vietnamese" },
  VOLAPÜK: { CODE: "vo", DISPLAY: "Volapük" },
  WALLOON: { CODE: "wa", DISPLAY: "Walloon" },
  WOLOF: { CODE: "wo", DISPLAY: "Wolof" },
  XHOSA: { CODE: "xh", DISPLAY: "Xhosa" },
  YIDDISH: { CODE: "yi", DISPLAY: "Yiddish" },
  YORUBA: { CODE: "yo", DISPLAY: "Yoruba" },
  "ZHUANG; CHUANG": { CODE: "za", DISPLAY: "Zhuang; Chuang" },
  CHINESE: { CODE: "zh", DISPLAY: "Chinese" },
  ZULU: { CODE: "zu", DISPLAY: "Zulu" },
};
